# This file goes in .streamlit/secrets.toml
# NEVER share this file publicly
# Replace with your actual keys

GROQ_API_KEY   = "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"
SARVAM_API_KEY = "sk_dwwwpzoz_N5mPLXAAClvBM59sziARHjEC"
